version: '4.26.1'
services: 
  backend: 
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 8000:8000
    volumes: 
      - .:/app
    depends_on:
      - db
  
  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: changemeinprod!
      POSTGRES_USER: postgres
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data