version: '4.26.1'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - CLOUDAMQP_URL=${CLOUDAMQP_URL}
      - HUB_SECRET_KEY=${HUB_SECRET_KEY}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - DB_SSL=${DB_SSL}

  db:
    image: postgres
    ports:
      - ${DOCKER_DB_PORT}
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
