# Generated by Django 5.0.2 on 2024-02-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0003_prompts_delete_hub'),
    ]

    operations = [
        migrations.AddField(
            model_name='actions',
            name='prompt',
            field=models.TextField(default=''),
        ),
    ]
