# Generated by Django 5.0.2 on 2024-02-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0004_actions_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actions',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
