# Generated by Django 5.0.2 on 2024-02-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0005_alter_actions_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='actions',
            name='success_criteria',
            field=models.TextField(default=''),
        ),
    ]
