# Generated by Django 5.0.2 on 2024-02-26 13:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0006_actions_success_criteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='actions',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
