name: Django CI

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        # Set options here if needed
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Build the Django Docker image
      run: docker build . --file Dockerfile --tag llama_hub

    - name: Wait for DB to be ready
      run: sleep 10

    - name: Run the Django container to execute migrations
      run: |
        docker run --network host \
        -e "DB_HOST=localhost" \
        -e "DB_PORT=5432" \
        -e "DB_NAME=test_db" \
        -e "DB_USERNAME=postgres" \
        -e "DB_PASSWORD=postgres" \
        llama_hub python manage.py migrate

    - name: Run tests in the Django container
      run: |
        docker run --network host \
        -e "DB_HOST=localhost" \
        -e "DB_PORT=5432" \
        -e "DB_NAME=test_db" \
        -e "DB_USERNAME=postgres" \
        -e "DB_PASSWORD=postgres" \
        llama_hub python manage.py test
