name: Django CI

on: [push]

permissions:
  id-token: write
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        # Set options here if needed
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Build the Django Docker image
      run: docker build . --file Dockerfile --tag llama_hub

    - name: Wait for DB to be ready
      run: sleep 10

    - name: Run the Django container to execute migrations
      run: |
        docker run --network host \
        -e "DB_HOST=localhost" \
        -e "DB_PORT=5432" \
        -e "DB_NAME=test_db" \
        -e "DB_USERNAME=postgres" \
        -e "DB_PASSWORD=postgres" \
        -e "HUB_SECRET_KEY=django-insecure-%x6%mb3ia1n^6^d98css88+ilj3aem2_^@)y5_8zhr#^9c_&(0" \
        llama_hub python manage.py migrate

    - name: Run tests in the Django container
      run: |
        docker run --network host \
        -e "DB_HOST=localhost" \
        -e "DB_PORT=5432" \
        -e "DB_NAME=test_db" \
        -e "DB_USERNAME=postgres" \
        -e "DB_PASSWORD=postgres" \
        -e "HUB_SECRET_KEY=django-insecure-%x6%mb3ia1n^6^d98css88+ilj3aem2_^@)y5_8zhr#^9c_&(0" \
        llama_hub python manage.py test

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::523425745135:role/GithubForDockerImages
        aws-region: us-east-1
        role-session-name: GitHubActions
  
    - name: Login to Amazon ECR Public
      run: aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/l9x3a2s9
  
    - name: Tag the Docker image
      run: docker tag llama_hub:latest public.ecr.aws/l9x3a2s9/speroautem:llama_hub

    - name: Push the Docker image to Amazon ECR Public
      run: docker push public.ecr.aws/l9x3a2s9/speroautem:llama_hub